### ISSUE TITLE
[Android Bootcamp] Project 0: Todo - Ready for Review

### ISSUE THREAD

**Issue by honghongw** [honghongw/MyToDoApp#1]
My app is complete, please review. Thanks! /cc @codepathreview @codepath

**Comment by nidhi1608** [comment]
Looks great! This was intended in part to give you an introduction to the general rhythm of this course. The course is entirely project based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer to learn all practical Android development and best practices as quickly as possible. We also do a code review for each submitted project.
Nice job with the project, hope you found it as a helpful introduction and see you on Friday!

**Comment by honghongw** [comment]
Thanks! :) 
![shipit](https://cloud.githubusercontent.com/assets/335519/8841931/9afc70dc-3126-11e5-8048-beb3bb1db52e.png)
